rabbit:
  image: "rabbitmq:3-management"
  hostname: "rabbit"
  environment:
    RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
    RABBITMQ_DEFAULT_USER: "root"
    RABBITMQ_DEFAULT_PASS: "root"
    RABBITMQ_DEFAULT_VHOST: "/"
  ports:
    - "15672:15672"
    - "5672:5672"